### ISSUE TITLE
Preserve directory structure with `complex_asset_package()`

### ISSUE THREAD

**Issue by marcelomgarcia** [carj/pyPreservica#10]
### Discussed in https://github.com/carj/pyPreservica/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **marcelomgarcia** December 27, 2022</sup>
Dear pyPreservica community

I have one question regarding the creation of packages (Upload API) with the `complex_asset_package():` is there a way to preserve directory structure when creating the package? 

When we use the method, we lose the directory structure, that is, the ZIP file is "flat" in the sense that all files are on the same directory, instead of, some files in their `data` folder: 

The original package:

```
C:\USERS\GARCM0B\WORK\REPO2PRESERVICA\DATA\IN\10754_652466
│   10754_652466.json
│   10754_652466.xml
│   592084-3870249.json
│   592084-3870249.pdf
│   592084-3870250.json
│   592084-3870250.pdf
│   592084-3870251.json
│   SHA256checksum.txt
│
└───data
        592084-3870251.metadata
        592084-3870251.pdf
```

Package from `complex_asset_package:`

```
C:\USERS\GARCM0B\WORK\REPO2PRESERVICA\PACKAGES\DA1B7DDA-632D-44CC-BE37-BAEC6932F192
└───da1b7dda-632d-44cc-be37-baec6932f192
    │   metadata.xml
    │
    └───content
            10754_652466.json
            10754_652466.xml
            592084-3870249.json
            592084-3870249.pdf
            592084-3870250.json
            592084-3870250.pdf
            592084-3870251.json
            592084-3870251.metadata
            592084-3870251.pdf
            SHA256checksum.txt

PS C:\Users\garcm0b\Work\repo2preservica\packages\da1b7dda-632d-44cc-be37-baec6932f192>
```

I was expecting to find a `data` directory inside the `content` folder.

We are creating the package like this:

```Python
import pyPreservica as PRES
(...)
def create_package(bagit_dir: path_to_dir, parent_folder: str) -> path_to_file:
    """Create a XIPv6 package (zip file) from the files in 'bagit_dir'
    and returns the path to the package"""

    path_files = []
    for root, dirs, files in os.walk(bagit_dir):
        path_files.extend(os.path.join(root, file) for file in files)

    package_path = PRES.complex_asset_package(
        preservation_files_list=path_files,
        parent_folder=parent_folder,
        Preservation_files_fixity_callback=PRES.Sha256FixityCallBack(),
        export_folder="packages",
    )

    return package_path
```

And a example of usage would be 

```Python
>>> bagit_dir = '10754_652466'
>>> path_files = []
>>> for root, dirs, files in os.walk(bagit_dir):  
...     path_files.extend(os.path.join(root, file) for file in files)
... 
>>> path_files
['10754_652466\\10754_652466.json', '10754_652466\\10754_652466.xml', '10754_652466\\592084-3870249.json', '10754_652466\\592084-3870249.pdf', '10754_652466\\592084-3870250.json', '10754_652466\\592084-3870250.pdf', '10754_652466\\592084-3870251.json', '10754_652466\\SHA256checksum.txt', '10754_652466\\data\\592084-3870251.metadata', '10754_652466\\data\\592084-3870251.pdf']
>>>  
```

So the `preservation_files_list` list contains the correct directory structure (with `data` dir.) , but the zip file lost this information.
</div>

**Comment by carj** [comment]
complex_asset_package() is designed to create a single Preservica asset containing one intellectual entity (this can be comprised of many digital objects). A LOC bag is a transfer container which may contain multiple intellectual entities, so there is not necessarily a one to one mapping between them.

Are you expecting to see the "data" structure as part of the Preservica asset?

**Comment by marcelomgarcia** [comment]
Yes, I would like to keep the `data` directory. 

From your description it seems that  `complex_asset_package(),` is what we need. The record (bag?) we download from the repository has this structure that we would like to keep when we create the package to ingest into Preservica.  If helps, the repository is based on DSpace.

**Comment by carj** [comment]
It may be possible to record the relative path of a digital file within the bitstream element, i.e the "data" folder, you would not necessarily see the structure in Preservica but it would be recorded in the AIP and be exposed when the asset was exported.

**Comment by marcelomgarcia** [comment]
Sorry for the late reply. I'm waiting for my colleague to evaluate what we should do. From my side, if the directory structure is restored when we extract the package, then for me it's fine. Next week, we can continue with the discussion.

**Comment by carj** [comment]
I have looked into this and have tried to create custom Preservica Assets which contain some internal structure, i.e relative paths within the content folder.

It looks like a Preservica Assets cannot contain any structure or folder information, any folders contained within the SIP under the content folder are removed and lost after the SIP is ingested. The result is that the Asset always has a flat structure once it has been ingested. The structure consists of a list of content objects at the same level. 

It is possible to create SIPs with internal structure and there is a use case for this, if you want to ingest multiple files with the same name you can add them to different folders inside the content directory.

But once the SIP has been ingested the internal folder structure is lost.

For example:

UUID/

       metadata.xml

       content/

                 folder1/

                            a.jpg

                folder2/

                            a.jpg

 

But this would result in an Asset with the structure

Asset/

         Representation 1/

                                   Content Object 1/

                                                              a.jpg

                                    Content Object 2/

                                                              a.jpg


Because the folder information is not preserved within the AIP, then you don’t recover the folder information if you export the Asset back out. If you export an asset you actually get an OPEX export which adds its own physical folder structure into the export to model the logical structures of the generations and representations etc.

If you absolutely need to preserve some kind of hierarchy or structure then using a mixture of Assets and Collections may be the way to go. 

This limitation is not connected to using the python library to create SIPs, it is a result of how the v6 data model holds archival packages so using a different method to create the SIPs would give the same result.

~

James
